Update got to 15.0.3
From the `got` changelog:

> response.rawBody and promise.buffer() now return a Uint8Array. Buffer
> is a subclass of Uint8Array, so most code will continue to work, but
> strict type checks will need updating.

Apparently our use case isn't "most cases" and stopped working because
we're calling `JSON.parse` on the buffer which works for `Buffer` (the
previous type of `rawBody`), but doesn't work so well on `Uint8Array`
(the new type). As you can see below, the uint array `toString` method
is spitting out bytes as a comma separated string.

```
> JSON.parse(Buffer.from('{}'))
{}
> JSON.parse(new Uint8Array([123, 125]))
Uncaught:
SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
> (new Uint8Array([123, 125])).toString()
'123,125'
```

The solution is fairly simple, we're using `got` with `responseType:
'text'` since f0fbe98da8, and `body` has always contained the decoded
string, the original code probably assumed that further transformations
were made to it and used rawBody but there's literally no point for this.

Closes #8419